### ISSUE TITLE
Set total supply field in token standard metadata

### ISSUE THREAD

**Issue by meiersi-da** [hyperledger-labs/splice#1252]
### Problem

We missed computing and setting `totalSupply` when implementing token standard support for Splice Amulet.

For example, Splice 0.4.3 reports the following on `/registry/metadata/v1/instruments`:
```
{
  "instruments": [
    {
      "id": "Amulet",
      "name": "Amulet",
      "symbol": "Amulet",
      "totalSupply": null,
      "totalSupplyAsOf": null,
      "decimals": 10,
      "supportedApis": {
        "splice-api-token-metadata-v1": 1,
        "splice-api-token-allocation-v1": 1,
        "splice-api-token-transfer-instruction-v1": 1,
        "splice-api-token-holding-v1": 1,
        "splice-api-token-allocation-instruction-v1": 1
      }
    }
  ],
  "nextPageToken": null
}
```

### Proposed solution

Use the internal functions backing `openapi/scan.yaml` as follows:

1. Query `/v0/round-of-latest-data`, which returns
   ```
    GetRoundOfLatestDataResponse:
      type: object
      required: ["round", "effectiveAt"]
      properties:
        round:
          type: integer
          format: int64
        effectiveAt:
          type: string
          format: date-time
   ```
2. Query `/v0/total-amulet-balance` using the `round` that was returned in the first call, which returns
   ```
   GetTotalAmuletBalanceResponse:
      type: object
      required: ["total_balance"]
      properties:
        total_balance:
          type: string
    ```
3. Set `totalSupply` to the `total_balance` and `totalSupplyAsOf` to `effectiveAt`

Note that this uses deprecated endpoints maintained by @ray-roestenburg-da's team.

@ray-roestenburg-da is that a problem, or will they stay around anyways? This seems like a straightforward implementation path. Do you agree with it, or do you have a better idea?

Note that the computation must be determinstic, so that BFT reads work when reading from Scan implementations of the same version. However future releases can change the implementation, so this shouldn't lock us in unnecessarily.
