### ISSUE TITLE
Make `app` labels on our k8s deployments more standard

### ISSUE THREAD

**Issue by canton-network-da** [hyperledger-labs/splice#558]
[ This issue was auto-migrated from DA's internal repo (DACH-NY/canton-network-node#18619). Original author: @martinflorian-da ]

## What is this about?

About our pod labels like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
```

Comment on https://github.com/hyperledger-labs/splice/pull/296

> best practice is to "namespace" them like : canton.network/app

## How important is this and why?

Low-prio polishing IMO
