### ISSUE TITLE
CCI static checks do not catch missing dependencies 

### ISSUE THREAD

**Issue by canton-network-da** [hyperledger-labs/splice#709]
[ This issue was auto-migrated from DA's internal repo (DACH-NY/canton-network-node#15168). Original author: @isegall-da ]

This is not caught by our static checks in `.circleci/build-config.sh` (which relies on CCI's `circleci config validate` tool)
![image](https://github.com/user-attachments/assets/d59ab20b-d4ec-4bef-8d6d-b400e31b0b66)

Hopefully we can get CCI to fix this in their static checker, I'm looking into opening a bug report with them.
If not, we may want to just implement it ourselves, as we repeatedly fall into this trap and don't even get notifications on these failures, just happen to notice them in CCI UI.

**Comment by canton-network-da** [comment]
[ from @isegall-da ]: Trying to reproduce this for a CCI bug report, seems like it's non-default workflows that do not get validated properly.

For this file, `circleci config validate .circleci/test.yml` passes:
```
version: 2.1

parameters:
  run-job:
    type: enum
    enum:
      [
        test,
        test2,
      ]
    default: test
jobs:
  a:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "this is job A"

workflows:
  j:
    when:
      equal: [ test2, << pipeline.parameters.run-job >> ]
    jobs:
      - a:
          requires:
            - does_not_exist
```

But changing the default of `run-job` to `test2`, and rerunning `circleci config validate .circleci/test.yml` fails with:
```
Error: config compilation contains errors: config compilation contains errors:
	- Job 'a' requires 'does_not_exist', which is the name of 0 other jobs in workflow 'j'
```
