### ISSUE TITLE
Automatically onboard first-time users in wallet UI

### ISSUE THREAD

**Issue by canton-network-da** [hyperledger-labs/splice#864]
[ This issue was auto-migrated from DA's internal repo (DACH-NY/canton-network-node#5206). Original author: @alexmatson-da ]

Instead of having an explicit onboarding page (as per discussion in a meeting with UX/design a little while back)

**Comment by branciard** [comment]
---

### 🔧 Feature Request: Add Helm Configuration to Control Auto-Onboarding

As a node provider, I would like more control over the wallet onboarding process to better align with our operational requirements and governance policies.

#### **Current Behavior:**
The wallet UI currently shows an auto-onboarding screen for unauthenticated users, allowing them to onboard themselves directly through the UI.

#### **Desired Behavior:**
For production deployments, we need the ability to disable auto-onboarding while maintaining wallet functionality for users who have been onboarded through our administrative processes.

---

### 💡 **Proposed Solution: Add `enableAutoOnboarding` Helm Configuration**

Adding a new Helm configuration option that allows administrators to control whether the auto-onboarding UI is displayed would address this need.

#### **Implementation Details:**

**1. Helm Configuration Changes:**

```yaml
# cluster/helm/splice-validator/values-template.yaml
enableWallet: true
# Control whether users can onboard themselves through the UI
enableAutoOnboarding: true
```

```yaml
# cluster/helm/splice-validator/templates/wallet-web-ui.yaml
- name: SPLICE_APP_UI_ENABLE_AUTO_ONBOARDING
  value: {{ .Values.enableAutoOnboarding | default true | quote }}
```

**2. Frontend Configuration:**

```typescript
// apps/wallet/frontend/src/utils/config.tsx
type WalletConfig = {
  // ... existing config
  enableAutoOnboarding?: boolean;
};

const configScheme = z.object({
  // ... existing schema
  enableAutoOnboarding: z.boolean().optional().default(true),
});
```

**3. UI Logic Update:**

```typescript
// apps/wallet/frontend/src/routes/authCheck.tsx
if (isOnboarded) {
  return <Outlet />;
} else {
  if (config.enableAutoOnboarding !== false) {
    return <Onboarding />;
  } else {
    return (
      <BasicLayout>
        <Grid /* ... */>
          <Typography variant="h4">Access Required</Typography>
          <Typography variant="body1">
            Please contact your administrator to be onboarded to use this wallet.
          </Typography>
        </Grid>
      </BasicLayout>
    );
  }
}
```

---

### ✅ **Benefits:**

- **Operational Control**: Administrators can manage user onboarding through their preferred processes
- **Backward Compatible**: Default `true` maintains current behavior for existing deployments
- **Flexible Deployment**: Different environments can use different onboarding approaches
- **Clean User Experience**: Clear messaging when auto-onboarding is disabled

---

### 🔧 **Usage:**

```yaml
# For administrator-controlled onboarding
enableAutoOnboarding: false

# For self-service onboarding (default)
enableAutoOnboarding: true
```

---

### 📋 **Context:**

The existing `enableWallet: false` option disables the entire wallet functionality, which is broader than needed. This proposal allows fine-grained control over just the onboarding process while preserving wallet functionality for properly onboarded users.

---

**Would the maintainers be interested in reviewing this feature request?**

---

### 🏷️ **Labels:**
`enhancement` `configuration` `helm` `wallet` `user-experience`
